cache = true
max_cache_age = "1d"

max_concurrency = 16
timeout = 10
retry_wait_time = 2
max_retries = 2

exclude_mail = true
exclude_loopback = true

exclude = [
  "https://coredocs.eu",
  "https://img.shields.io",
  "https://shields.io",
  "https://discord.gg",
]

scheme = ["https"]
fail = "all"
