name: Link Check
on: [push, pull_request, workflow_dispatch]

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --config lychee.toml
            --verbose
            --no-progress
            --max-concurrency 16
            --timeout 10
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
