name: Lint NetBox Scripts (soft)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint (errors only, ignore NetBox imports)
        run: |
          pylint -E --disable=import-error scripts/*.py
